FROM nvidia/cuda:12.1.0-devel-ubuntu22.04

WORKDIR /workspace

# install build and runtime dependencies
COPY requirements.txt /
RUN apt-get update -y \
    && apt-get install -y python3-pip git
RUN pip config set global.index-url https://mirrors.ustc.edu.cn/pypi/web/simple
# RUN pip config set install.trusted-host mirrors.aliyun.com
RUN --mount=type=cache,target=/root/.cache/pip \
    pip install -r /requirements.txt

# add code to docker and specify cuda arch
ARG torch_cuda_arch_list='7.0 8.0 8.6+PTX'
ENV TORCH_CUDA_ARCH_LIST=${torch_cuda_arch_list}

COPY . /opt/vllm-main/
RUN cd /opt/vllm-main && python3 setup.py install

# change workdir to /workspace/app
WORKDIR /workspace/app
COPY entrypoint.sh /workspace/app/entrypoint.sh
COPY gpu_count.py /workspace/app/gpu_count.py 

RUN chmod 755 entrypoint.sh 
ENTRYPOINT ["./entrypoint.sh"]
